version: "3.9"

services:
  ingestion_service:
    build: 
      context: .
      dockerfile: ingestion_service/Dockerfile
    volumes:
      - shared_data:/app/data
    command: python ingestion_service/ingestion.py

  processing_service:
    build:
      context: .
      dockerfile: processing_service/Dockerfile
    volumes:
      - shared_data:/app/data
    command: python processing_service/processing.py

  transformation_service:
    build:
      context: .
      dockerfile: transformation_service/Dockerfile
    volumes:
      - shared_data:/app/data
    command: python transformation_service/transform.py
  
  api_service:
    build:
      context: .
      dockerfile: api_service/Dockerfile
    volumes:
      - shared_data:/app/data
    ports:
      - "8000:8000"
    command: uvicorn api_service.main:app --host 0.0.0.0 --port 8000
  
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    volumes:
      - shared_data:/app/data
    command: python orchestrator/main.py

volumes:
  shared_data: